# Generated by Django 3.1.3 on 2020-11-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201129_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='image_name',
            field=models.FileField(upload_to=''),
        ),
    ]
