# Generated by Django 3.1.3 on 2020-11-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201130_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
