# Generated by Django 3.1.3 on 2020-11-30 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201130_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='image_name',
        ),
    ]
