# Generated by Django 3.1.3 on 2020-11-30 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_laptop_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='image_name',
        ),
    ]
