# Generated by Django 3.1.3 on 2020-11-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201130_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='brand',
        ),
        migrations.AddField(
            model_name='laptop',
            name='brandj',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
