# Generated by Django 3.1.3 on 2020-11-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201130_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='brandj',
            new_name='brand',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
