# Generated by Django 3.1.3 on 2020-11-30 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201130_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='image',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='display',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='memory_hdd',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='memory_ram',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='price',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='processor',
        ),
    ]
